---
output: html_document
---
```{r, echo=F}
library(xtable)
library(Matrix)
###############################################
# temporarily load data from REPORT DIRECTORY #
# this is for initially writting the file     #
# change to load from TOP DIRECTORY when done #
###############################################

load(file = "../../data/lm-model.RData")
load(file = "../../data/ridge-models.RData")
load(file = "../../data/lasso-models.RData")
load(file = "../../data/pls-models.RData")
load(file = "../../data/pcr-models.RData")

# read in original data, tests and training sets as well
data = as.matrix(read.csv("../../data/scaled-credit.csv", row.names = 1))
x.train = as.matrix(read.csv("../../data/xtrain.csv", row.names = 1))
y.train = as.matrix(read.csv("../../data/ytrain.csv", row.names = 1))
x.test = as.matrix(read.csv("../../data/xtest.csv", row.names = 1))
y.test = as.matrix(read.csv("../../data/ytest.csv", row.names = 1))
```
#Conclusion
Over the course of this project we have modeled the `Credit.csv` data in several ways. We began by cleaning and preparing the data, analyzing individual regressors (qualitative and quantitative) for any interesting facts, centering and standardizing the data, as well as factoring out levels of qualitative variables (i.e `Married` became `MarriedYes` with 0 for a `No` response and 1 for `Yes`). In preparation for building future models, we also partitioned the data into test and training sets. We chose not to cross-validate the linear model since it is simply a benchmark, we fully expect our models to outpreform this.

Next we created a baseline model to compare all other models to, for this we used a simple linear regression. This yielded a surprisingly good MSE of `r linearMSE`. Our next approach was to try cross-validated ridge and lasso regressions, which are shrinkage methods. Through crossvalidation we found the optimal lamb Both ridge and lasso of these yielded much better cross-validated MSEs of `r cvRidgeMSE` and `r cvLassoMSE` respectively. Finally, we considered Partial Component Regression (PCR) and Partial Least Squares (PLS) which both yielded cross-validated MSE's of `r cvPcrMSE` and `r cvPlsMSE`.

From this data is it clear that the ridge reggression model was the most effective at modeling the `Credit.csv` data.
